[package]
name = "binreader-rust"
version = "0.3.1"
authors = ["autergame"]

[dependencies]
byteorder = "1.4.3"
json = "0.12.4"
dtoa = "1.0.9"
clap = "4.3.17"
glob = "0.3.1"

[profile]
release = { strip = true }